# Generated by Django 5.2.6 on 2025-09-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
