# Generated by Django 5.2.6 on 2025-09-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_alter_booking_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
